const express=require("express")
const dotenv=require("dotenv")
const mongoose=require("mongoose")
const cors=require("cors")
const complaintRoute=require("./routes/complaint")
const feedBackRoute=require("./routes/feedback")
const adminAuth=require("./routes/adminAuth")
dotenv.config()

const app=express()
app.use(cors())
app.use(express.json())
app.use("/api/complaints",complaintRoute)
app.use("/api/feedback",feedBackRoute)
app.use((req,res,next)=>{
    res.header("Access-Control-Allow-Origin","*")
    res.header("Access-Control-Allow-Headers","Origin,X-Requested-With,Content-Type,Accept")
    next()
})
app.use("/api/auth",adminAuth)
mongoose.connect(process.env.DB_URL)
.then(()=>console.log("Connected to MongoDB"))  
.catch((err)=>console.log(err))
const port=process.env.PORT;
app.listen(port,()=>console.log(`The server is running on port ${port}`))