import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'rw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'home': 'Home',
    'submit': 'Submit Complaint',
    'track': 'Track Complaint',
    'login': 'Staff Login',
    // Index.tsx
    'hero.title': 'Citizen Engagement System',
    'hero.subtitle': 'Submit your feedback and complaints about public services in Rwanda easily and securely.',
    'hero.submit': 'Submit Complaint',
    'hero.track': 'Track Complaint',
    'howItWorks.title': 'How It Works',
    'howItWorks.submit': 'Submit',
    'howItWorks.submitDesc': 'Fill out the complaint form with your feedback about the service.',
    'howItWorks.track': 'Track',
    'howItWorks.trackDesc': 'Use your complaint number to track its progress.',
    'howItWorks.response': 'Response',
    'howItWorks.responseDesc': 'Get updates on your complaint status through this system.',
    'categories.title': 'Complaint Categories',
    'categories.education': 'Education Issues',
    'categories.healthcare': 'Healthcare Issues',
    'categories.business': 'Business Issues',
    'categories.infrastructure': 'Infrastructure Issues',
    'readMore': 'Read More',
    'stats.title': 'Trusted by Rwandan Citizens',
    'stats.subtitle': 'Many citizens use this system to submit their feedback and complaints',
    'stats.users': 'System Users',
    'stats.rating': 'User Rating',
    'stats.resolved': 'Issues Resolved',
    'feedback.title': 'Share Your Feedback',
    'feedback.subtitle': 'Your feedback is important for improving our services. Let us know what you think.',
    'feedback.feedback': 'Feedback *',
    'feedback.feedbackPlaceholder': 'Write your feedback here...',
    'feedback.province': 'Province *',
    'feedback.district': 'District *',
    'feedback.sector': 'Sector',
    'feedback.cell': 'Cell *',
    'feedback.village': 'Village *',
    'feedback.email': 'Email',
    'feedback.phone': 'Phone',
    'feedback.submit': 'Submit Feedback',
    'cta.title': 'Ready to share your feedback?',
    'cta.subtitle': 'Our feedback system helps you communicate with the right government officials.',
    'cta.button': 'Submit Complaint Now',
    // Feedback validation errors
    'errors.feedbackRequired': 'Please write your feedback.',
    'errors.provinceRequired': 'Please select a province.',
    'errors.districtRequired': 'Please enter a district.',
    'errors.cellRequired': 'Please enter a cell.',
    'errors.villageRequired': 'Please enter a village.',
    'errors.requiredFields': 'Please fill in all required fields.',

    // SubmitComplaint.tsx
    'submit.title': 'Submit a Complaint',
    'submit.subtitle': 'Fill in the form below to submit your complaint or feedback about a public service in Rwanda.',
    'submit.fullName': 'Full Name',
    'submit.nationalId': 'National ID',
    'submit.email': 'Email',
    'submit.phone': 'Phone Number',
    'submit.province': 'Province',
    'submit.district': 'District',
    'submit.sector': 'Sector',
    'submit.cell': 'Cell',
    'submit.village': 'Village',
    'submit.serviceType': 'Type of Service',
    'submit.description': 'Description',
    'submit.descriptionPlaceholder': 'Please describe your complaint in detail',
    'submit.fullNamePlaceholder': 'Enter your full name',
    'submit.nationalIdPlaceholder': 'Enter your National ID',
    'submit.emailPlaceholder': 'Enter your email',
    'submit.phonePlaceholder': 'Enter your phone number',
    'submit.selectProvince': 'Select province',
    'submit.selectDistrict': 'Select district',
    'submit.selectSector': 'Select sector',
    'submit.selectCell': 'Select cell',
    'submit.selectVillage': 'Select village',
    'submit.selectServiceType': 'Select service type',
    'submit.cancel': 'Cancel',
    'submit.submit': 'Submit Complaint',
    'submit.submitting': 'Submitting...',

    // TrackComplaint.tsx
    'track.title': 'Track Your Complaint',
    'track.subtitle': 'Enter your complaint number to view its status.',
    'track.code': 'Complaint Number',
    'track.codePlaceholder': 'Enter complaint number',
    'track.loading': 'Searching...',
    'track.button': 'Search Complaint',
    'track.error': 'Error tracking complaint.',
    'track.complaintDetails': 'Complaint Details',
    'track.submittedOn': 'Submitted on',
    'track.submitted': 'Submitted on date',
    'track.type': 'Complaint Type',
    'track.location': 'Location',
    'track.sector': 'Sector',
    'track.village': 'Village',
    'track.description': 'Description',
    'track.response': 'Response',
    'track.respondedBy': 'Responded by',
    'track.responseDate': 'Response Date',
    'track.saveNumber': 'Save complaint number',
    'track.contact': 'Contact Information',
    'track.email': 'Email',
    'track.phone': 'Phone',
    'errors.trackingCode': 'Please enter a tracking code.',
    'errors.tracking': 'Failed to track complaint. Please check the number and try again.',

    // Complaint Categories
    'categories.waterSupply': 'Water Supply',
    'categories.electricity': 'Electricity',
    'categories.roads': 'Roads',
    
    'categories.sanitation': 'Sanitation',
    'categories.publicTransport': 'Public Transport',
    'categories.security': 'Security',
    'categories.landServices': 'Land Services',
    'categories.other': 'Other',

    // Subcategories
    'subcategories.serviceInterruption': 'Service Interruption',
    'subcategories.qualityIssues': 'Quality Issues',
    'subcategories.billingProblems': 'Billing Problems',
    'subcategories.connectionProblems': 'Connection Problems',
    'subcategories.powerOutage': 'Power Outage',
    'subcategories.voltageIssues': 'Voltage Issues',
    'subcategories.potholes': 'Potholes',
    'subcategories.trafficSignals': 'Traffic Signals',
    'subcategories.roadSigns': 'Road Signs',
    'subcategories.constructionIssues': 'Construction Issues',
    'subcategories.serviceQuality': 'Service Quality',
    'subcategories.medicationIssues': 'Medication Issues',
    'subcategories.staffBehavior': 'Staff Behavior',
    'subcategories.facilities': 'Facilities',
    'subcategories.schoolFacilities': 'School Facilities',
    'subcategories.teacherIssues': 'Teacher Issues',
    'subcategories.curriculum': 'Curriculum',
    'subcategories.administration': 'Administration',
    'subcategories.wasteCollection': 'Waste Collection',
    'subcategories.publicToilets': 'Public Toilets',
    'subcategories.drainage': 'Drainage',
    'subcategories.cleanliness': 'Cleanliness',
    'subcategories.serviceFrequency': 'Service Frequency',
    'subcategories.driverBehavior': 'Driver Behavior',
    'subcategories.vehicleCondition': 'Vehicle Condition',
    'subcategories.routes': 'Routes',
    'subcategories.policeResponse': 'Police Response',
    'subcategories.crimeReporting': 'Crime Reporting',
    'subcategories.safetyConcerns': 'Safety Concerns',
    'subcategories.patrols': 'Patrols',
    'subcategories.registration': 'Registration',
    'subcategories.surveying': 'Surveying',
    'subcategories.documentation': 'Documentation',
    'subcategories.disputes': 'Disputes',
    'subcategories.generalComplaint': 'General Complaint',
    'subcategories.suggestion': 'Suggestion',
    'subcategories.inquiry': 'Inquiry',
    'subcategories.feedback': 'Feedback',

    // Form validation messages
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.phone': 'Please enter a valid phone number',
    'validation.nationalId': 'Please enter a valid National ID',
    'validation.minLength': 'This field must be at least {min} characters',
    'validation.maxLength': 'This field must not exceed {max} characters',
    'validation.onlyLetters': 'This field can only contain letters',
    'validation.onlyNumbers': 'This field can only contain numbers',
    'validation.onlyLettersAndNumbers': 'This field can only contain letters and numbers',
    'validation.onlyLettersAndSpaces': 'This field can only contain letters and spaces',
    'validation.onlyNumbersAndSpaces': 'This field can only contain numbers and spaces',
    'validation.onlyLettersNumbersAndSpaces': 'This field can only contain letters, numbers and spaces',
    'validation.onlyLettersNumbersAndSpecialChars': 'This field can only contain letters, numbers and special characters',
    'validation.onlyLettersAndSpecialChars': 'This field can only contain letters and special characters',
    'validation.onlyNumbersAndSpecialChars': 'This field can only contain numbers and special characters',
    'validation.onlySpecialChars': 'This field can only contain special characters',
    'validation.onlyLettersAndHyphens': 'This field can only contain letters and hyphens',
    'validation.onlyNumbersAndHyphens': 'This field can only contain numbers and hyphens',
    'validation.onlyLettersNumbersAndHyphens': 'This field can only contain letters, numbers and hyphens',
    'validation.onlyLettersAndUnderscores': 'This field can only contain letters and underscores',
    'validation.onlyNumbersAndUnderscores': 'This field can only contain numbers and underscores',
    'validation.onlyLettersNumbersAndUnderscores': 'This field can only contain letters, numbers and underscores',
    'validation.onlyLettersAndDots': 'This field can only contain letters and dots',
    'validation.onlyNumbersAndDots': 'This field can only contain numbers and dots',
    'validation.onlyLettersNumbersAndDots': 'This field can only contain letters, numbers and dots',
    'validation.onlyLettersAndCommas': 'This field can only contain letters and commas',
    'validation.onlyNumbersAndCommas': 'This field can only contain numbers and commas',
    'validation.onlyLettersNumbersAndCommas': 'This field can only contain letters, numbers and commas',
    'validation.onlyLettersAndSlashes': 'This field can only contain letters and slashes',
    'validation.onlyNumbersAndSlashes': 'This field can only contain numbers and slashes',
    'validation.onlyLettersNumbersAndSlashes': 'This field can only contain letters, numbers and slashes',
    'validation.onlyLettersAndBackslashes': 'This field can only contain letters and backslashes',
    'validation.onlyNumbersAndBackslashes': 'This field can only contain numbers and backslashes',
    'validation.onlyLettersNumbersAndBackslashes': 'This field can only contain letters, numbers and backslashes',
    'validation.onlyLettersAndColons': 'This field can only contain letters and colons',
    'validation.onlyNumbersAndColons': 'This field can only contain numbers and colons',
    'validation.onlyLettersNumbersAndColons': 'This field can only contain letters, numbers and colons',
    'validation.onlyLettersAndSemicolons': 'This field can only contain letters and semicolons',
    'validation.onlyNumbersAndSemicolons': 'This field can only contain numbers and semicolons',
    'validation.onlyLettersNumbersAndSemicolons': 'This field can only contain letters, numbers and semicolons',
    'validation.onlyLettersAndAmpersands': 'This field can only contain letters and ampersands',
    'validation.onlyNumbersAndAmpersands': 'This field can only contain numbers and ampersands',
    'validation.onlyLettersNumbersAndAmpersands': 'This field can only contain letters, numbers and ampersands',
    'validation.onlyLettersAndAsterisks': 'This field can only contain letters and asterisks',
    'validation.onlyNumbersAndAsterisks': 'This field can only contain numbers and asterisks',
    'validation.onlyLettersNumbersAndAsterisks': 'This field can only contain letters, numbers and asterisks',
    'validation.onlyLettersAndPlusSigns': 'This field can only contain letters and plus signs',
    'validation.onlyNumbersAndPlusSigns': 'This field can only contain numbers and plus signs',
    'validation.onlyLettersNumbersAndPlusSigns': 'This field can only contain letters, numbers and plus signs',
    'validation.onlyLettersAndEqualsSigns': 'This field can only contain letters and equals signs',
    'validation.onlyNumbersAndEqualsSigns': 'This field can only contain numbers and equals signs',
    'validation.onlyLettersNumbersAndEqualsSigns': 'This field can only contain letters, numbers and equals signs',
    'validation.onlyLettersAndQuestionMarks': 'This field can only contain letters and question marks',
    'validation.onlyNumbersAndQuestionMarks': 'This field can only contain numbers and question marks',
    'validation.onlyLettersNumbersAndQuestionMarks': 'This field can only contain letters, numbers and question marks',
    'validation.onlyLettersAndExclamationMarks': 'This field can only contain letters and exclamation marks',
    'validation.onlyNumbersAndExclamationMarks': 'This field can only contain numbers and exclamation marks',
    'validation.onlyLettersNumbersAndExclamationMarks': 'This field can only contain letters, numbers and exclamation marks',
    'validation.onlyLettersAndAtSigns': 'This field can only contain letters and at signs',
    'validation.onlyNumbersAndAtSigns': 'This field can only contain numbers and at signs',
    'validation.onlyLettersNumbersAndAtSigns': 'This field can only contain letters, numbers and at signs',
    'validation.onlyLettersAndHashSigns': 'This field can only contain letters and hash signs',
    'validation.onlyNumbersAndHashSigns': 'This field can only contain numbers and hash signs',
    'validation.onlyLettersNumbersAndHashSigns': 'This field can only contain letters, numbers and hash signs',
    'validation.onlyLettersAndDollarSigns': 'This field can only contain letters and dollar signs',
    'validation.onlyNumbersAndDollarSigns': 'This field can only contain numbers and dollar signs',
    'validation.onlyLettersNumbersAndDollarSigns': 'This field can only contain letters, numbers and dollar signs',
    'validation.onlyLettersAndPercentSigns': 'This field can only contain letters and percent signs',
    'validation.onlyNumbersAndPercentSigns': 'This field can only contain numbers and percent signs',
    'validation.onlyLettersNumbersAndPercentSigns': 'This field can only contain letters, numbers and percent signs',
    'validation.onlyLettersAndCaretSigns': 'This field can only contain letters and caret signs',
    'validation.onlyNumbersAndCaretSigns': 'This field can only contain numbers and caret signs',
    'validation.onlyLettersNumbersAndCaretSigns': 'This field can only contain letters, numbers and caret signs',

    // Footer.tsx
    'footer.description': 'Citizen Engagement System for submitting and tracking complaints and feedback on public services in Rwanda.',
    'footer.links.title': 'Quick Links',
    'footer.links.home': 'Home',
    'footer.links.submit': 'Submit Complaint',
    'footer.links.track': 'Track Complaint',
    'footer.contact.title': 'Contact Us',
    'footer.contact.location': 'Kigali, Rwanda',
    'footer.contact.email': 'support@cesrwanda.gov.rw',
    'footer.contact.phone': '+250 788 123 456',
    'footer.copyright': 'Ivugire. All rights reserved.',
    'submit.success': 'Your complaint has been submitted successfully!',
    'submit.successMessage':"you have submitted complaint successfully",
    'submit.error':'Failed to send complaint',
    'submit.errorMessage': 'Failed to submit complaint. Please try again.',

    // Feedback Section
    'feedback.selectProvincePlaceholder': 'Select province',
    'feedback.selectDistrictPlaceholder': 'Select district',
    'feedback.selectSectorPlaceholder': 'Select sector',
    'feedback.selectCellPlaceholder': 'Select cell',
    'feedback.selectVillagePlaceholder': 'Select village',
    'feedback.emailPlaceholder': 'Enter your email',
    'feedback.phonePlaceholder': 'Enter your phone number',
    'feedback.successMessage': 'Feedback sent successfully!',
    'feedback.errorMessage': 'Failed to send feedback. Please try again.',
  },
  rw: {
    // Navigation
    'home': 'Ahabanza',
    'submit': 'Tanga Ikibazo',
    'track': 'Kureba Ikibazo',
    'login': 'Kwinjira',
    // Index.tsx
    'hero.title': 'Sisitemu yo Gutanga Ibitekerezo',
    'hero.subtitle': 'Ikoreshwa mu gutanga ibitekerezo n ibibazo ku mirimo ya Leta mu Rwanda byoroshye kandi mu mucyo.',
    'hero.submit': 'Tanga Ikibazo',
    'hero.track': 'Kureba Aho Ikibazo Kigeze',
    'howItWorks.title': 'Uko Bikorwa',
    'howItWorks.submit': 'Tanga',
    'howItWorks.submitDesc': 'Uzuza ifishi y ikibazo ibitekerezo byawe ku bijyanye na serivisi.',
    'howItWorks.track': 'Kurikirana',
    'howItWorks.trackDesc': 'Koresha nimero y ikibazo cyawe kugira ngo ukurikirane aho kigeze.',
    'howItWorks.response': 'Igisubizo',
    'howItWorks.responseDesc': 'Kubona amakuru ku gikemuro cy ikibazo cyawe ukoresheje iyi sisitemu.',
    'categories.title': 'Amoko yIbibazo',
    'categories.education': 'Ibibazo Mu Burezi',
    'categories.healthcare': 'Ibibazo Mu Buvuzi',
    'categories.business': 'Ibibazo Mu Bucuruzi',
    'categories.infrastructure': 'Ibibazo Mu Bikorwa Remezo',
    'readMore': 'Soma Ibindi',
    'stats.title': 'Byakunzwe n Abaturage bo mu Rwanda',
    'stats.subtitle': 'Abaturage benshi bakoresha iyi sisitemu yo gutanga ibitekerezo n ibibazo byabo',
    'stats.users': 'Abakoresha sisitemu',
    'stats.rating': 'Amanota batanga',
    'stats.resolved': 'Ibibazo byakemurwa',
    'feedback.title': 'Tubwire Ibitekerezo',
    'feedback.subtitle': 'Ibitekerezo byawe ni ingenzi mu guteza imbere serivisi zacu. Tubwire icyo utekereza.',
    'feedback.feedback': 'Igitekerezo *',
    'feedback.feedbackPlaceholder': 'Andika hano igitekerezo cyawe...',
    'feedback.province': 'Intara *',
    'feedback.district': 'Akarere *',
    'feedback.sector': 'Umurenge',
    'feedback.cell': 'Akagari *',
    'feedback.village': 'Umudugudu *',
    'feedback.email': 'Imeli',
    'feedback.phone': 'Telefoni',
    'feedback.submit': 'Ohereza Ibitekerezo',
    'cta.title': 'Witegure gutanga igitekerezo cyawe?',
    'cta.subtitle': 'Sisitemu yacu yo gutanga ibitekerezo igufasha kuvugana n abakozi ba Leta bakwiye.',
    'cta.button': 'Tanga Ikibazo Nonaha',
    'validation.required': 'Uzuza Imyanya yose',

    // Feedback validation errors
    'errors.feedbackRequired': 'Andika igitekerezo cyawe.',
    'errors.provinceRequired': 'Hitamo intara.',
    'errors.districtRequired': 'Andika akarere.',
    'errors.cellRequired': 'Andika akagari.',
    'errors.villageRequired': 'Andika umudugudu.',
    'errors.requiredFields': 'Nyamuneka wujuze ibisabwa.',

    // SubmitComplaint.tsx
    'submit.title': 'Tanga Ikibazo',
    'submit.subtitle': 'Uzuza ifishi iri munsi yo gutanga ikibazo cyawe cyangwa igitekerezo ku bijyanye na serivisi ya Leta mu Rwanda.',
    'submit.fullName': 'Amazina Yombi',
    'submit.nationalId': 'Indangamuntu',
    'submit.email': 'Imeli',
    'submit.phone': 'Telefoni',
    'submit.province': 'Intara',
    'submit.district': 'Akarere',
    'submit.sector': 'Umurenge',
    'submit.cell': 'Akagari',
    'submit.village': 'Umudugudu',
    'submit.serviceType': 'Ubwoko bw ikibazo',
    'submit.description': 'Inshamake',
    'submit.descriptionPlaceholder': 'Nyamuneka vuga inshamake y ikibazo cyawe',
    'submit.fullNamePlaceholder': 'Andika amazina yawe yombi',
    'submit.nationalIdPlaceholder': 'Andika indangamuntu yawe',
    'submit.emailPlaceholder': 'Andika imeli yawe',
    'submit.phonePlaceholder': 'Andika nimero ya telefoni yawe',
    'submit.selectProvince': 'Hitamo intara',
    'submit.selectDistrict': 'Hitamo akarere',
    'submit.selectSector': 'Hitamo umurenge',
    'submit.selectCell': 'Hitamo akagari',
    'submit.selectVillage': 'Hitamo umudugudu',
    'submit.selectServiceType': 'Hitamo ubwoko bw ikibazo',
    'submit.cancel': 'Reka',
    'submit.submit': 'Ohereza Ikibazo',
    'submit.submitting': 'Arikoherezwa...',
    'submit.success':'ikibazo cyoherejwe neza',
    'submit.successMessage':'kohereza ikibazo byakunze',
    'submit.error':'Kohereza ikibazo byanze',
    'submit.errorMessage': 'Kohereza ikibazo ntibyabashije gukunda',


    // TrackComplaint.tsx
    'track.title': 'Kureba Aho Ikibazo Kigeze',
    'track.subtitle': 'Andika nimero yikibazo cyawe uzahabwa amakuru kuri cyo.',
    'track.code': 'Nimero y Ikibazo',
    'track.codePlaceholder': 'Andika nimero y ikibazo',
    'track.loading': 'Turitegereje...',
    'track.button': 'Reba Ikibazo',
    'track.error': 'Hari ikibazo mu kureba ikibazo.',
    'track.complaintDetails': 'Amakuru y ikibazo',
    'track.submittedOn': 'Cyashyizweho',
    'track.submitted': 'Cyashyizweho ku itariki',
    'track.type': 'Ubwoko bw ikibazo',
    'track.location': 'Aho kiri',
    'track.sector': 'Umurenge',
    'track.village': 'Umudugudu',
    'track.description': 'Inshamake',
    'track.response': 'Igisubizo',
    'track.respondedBy': 'Byatanzwe na',
    'track.responseDate': 'Itariki y igisubizo',
    'track.saveNumber': 'Shyira nimero mu bubiko',
    'track.contact': 'Amakuru y umuntu',
    'track.email': 'Imeli',
    'track.phone': 'Telefoni',
    'errors.trackingCode': 'Nyamuneka andika nimero y ikibazo.',
    'errors.tracking': 'Kureba ikibazo byanze. Nyamuneka reba nimero wongere ugerageze.',

    // Complaint Categories
    'categories.waterSupply': 'Amazi',
    'categories.electricity': 'Umuriro',
    'categories.roads': 'Inzira',
    
    'categories.sanitation': 'Isuku',
    'categories.publicTransport': 'Ubwizungu',
    'categories.security': 'Umutekano',
    'categories.landServices': 'Serivisi z ubutaka',
    'categories.other': 'Ibindi',

    // Subcategories
    'subcategories.serviceInterruption': 'Guhagarika serivisi',
    'subcategories.qualityIssues': 'Ibibazo by ubwiza',
    'subcategories.billingProblems': 'Ibibazo by amafaranga',
    'subcategories.connectionProblems': 'Ibibazo by ukwihuza',
    'subcategories.powerOutage': 'Guhagarika umuriro',
    'subcategories.voltageIssues': 'Ibibazo by agaciro k umuriro',
    'subcategories.potholes': 'Ibirundiro',
    'subcategories.trafficSignals': 'Ibirambo',
    'subcategories.roadSigns': 'Ibirambo by inzira',
    'subcategories.constructionIssues': 'Ibibazo by ubwubatsi',
    'subcategories.serviceQuality': 'Ubwiza bwa serivisi',
    'subcategories.medicationIssues': 'Ibibazo by imiti',
    'subcategories.staffBehavior': 'Imikorere y abakozi',
    'subcategories.facilities': 'Ibikorwa remezo',
    'subcategories.schoolFacilities': 'Ibikorwa remezo by ishuri',
    'subcategories.teacherIssues': 'Ibibazo by abarimu',
    'subcategories.curriculum': 'Amasomo',
    'subcategories.administration': 'Ubuyobozi',
    'subcategories.wasteCollection': 'Gukurura imyanda',
    'subcategories.publicToilets': 'Icyumba cy amahoro',
    'subcategories.drainage': 'Amazi y imvura',
    'subcategories.cleanliness': 'Isuku',
    'subcategories.serviceFrequency': 'Ubwinshi bwa serivisi',
    'subcategories.driverBehavior': 'Imikorere y umushoferi',
    'subcategories.vehicleCondition': 'Imiterere y imodoka',
    'subcategories.routes': 'Inzira',
    'subcategories.policeResponse': 'Igisubizo cy abapolisi',
    'subcategories.crimeReporting': 'Kumenyesha ibyaha',
    'subcategories.safetyConcerns': 'Ibibazo by umutekano',
    'subcategories.patrols': 'Kuronda',
    'subcategories.registration': 'Kwiyandikisha',
    'subcategories.surveying': 'Gukurura',
    'subcategories.documentation': 'Inyandiko',
    'subcategories.disputes': 'Amakimbirane',
    'subcategories.generalComplaint': 'Ikibazo rusange',
    'subcategories.suggestion': 'Icyifuzo',
    'subcategories.inquiry': 'Ikibazo',
    'subcategories.feedback': 'Igitekerezo',

    // Form validation messages
    'validation.email': 'Nyamuneka andika imeli yemewe',
    'validation.phone': 'Nyamuneka andika nimero ya telefoni yemewe',
    'validation.nationalId': 'Nyamuneka andika indangamuntu yemewe',
    'validation.minLength': 'Iki gice gisabwa kuba gifite {min} inyuguti',
    'validation.maxLength': 'Iki gice gisabwa kutarenze {max} inyuguti',
    'validation.onlyLetters': 'Iki gice gisabwa kuba gifite inyuguti gusa',
    'validation.onlyNumbers': 'Iki gice gisabwa kuba gifite imibare gusa',
    'validation.onlyLettersAndNumbers': 'Iki gice gisabwa kuba gifite inyuguti n imibare gusa',
    'validation.onlyLettersAndSpaces': 'Iki gice gisabwa kuba gifite inyuguti n imyanya gusa',
    'validation.onlyNumbersAndSpaces': 'Iki gice gisabwa kuba gifite imibare n imyanya gusa',
    'validation.onlyLettersNumbersAndSpaces': 'Iki gice gisabwa kuba gifite inyuguti, imibare n imyanya gusa',
    'validation.onlyLettersNumbersAndSpecialChars': 'Iki gice gisabwa kuba gifite inyuguti, imibare n inyuguti zihariye gusa',
    'validation.onlyLettersAndSpecialChars': 'Iki gice gisabwa kuba gifite inyuguti n inyuguti zihariye gusa',
    'validation.onlyNumbersAndSpecialChars': 'Iki gice gisabwa kuba gifite imibare n inyuguti zihariye gusa',
    'validation.onlySpecialChars': 'Iki gice gisabwa kuba gifite inyuguti zihariye gusa',
    'validation.onlyLettersAndHyphens': 'Iki gice gisabwa kuba gifite inyuguti n impambano gusa',
    'validation.onlyNumbersAndHyphens': 'Iki gice gisabwa kuba gifite imibare n impambano gusa',
    'validation.onlyLettersNumbersAndHyphens': 'Iki gice gisabwa kuba gifite inyuguti, imibare n impambano gusa',
    'validation.onlyLettersAndUnderscores': 'Iki gice gisabwa kuba gifite inyuguti n impambano gusa',
    'validation.onlyNumbersAndUnderscores': 'Iki gice gisabwa kuba gifite imibare n impambano gusa',
    'validation.onlyLettersNumbersAndUnderscores': 'Iki gice gisabwa kuba gifite inyuguti, imibare n impambano gusa',
    'validation.onlyLettersAndDots': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndDots': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndDots': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndCommas': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndCommas': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndCommas': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndSlashes': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndSlashes': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndSlashes': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndBackslashes': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndBackslashes': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndBackslashes': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndColons': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndColons': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndColons': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndSemicolons': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndSemicolons': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndSemicolons': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndAmpersands': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndAmpersands': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndAmpersands': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndAsterisks': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndAsterisks': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndAsterisks': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndPlusSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndPlusSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndPlusSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndEqualsSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndEqualsSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndEqualsSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndQuestionMarks': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndQuestionMarks': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndQuestionMarks': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndExclamationMarks': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndExclamationMarks': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndExclamationMarks': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndAtSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndAtSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndAtSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndHashSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndHashSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndHashSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndDollarSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndDollarSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndDollarSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndPercentSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndPercentSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndPercentSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',
    'validation.onlyLettersAndCaretSigns': 'Iki gice gisabwa kuba gifite inyuguti n amabara gusa',
    'validation.onlyNumbersAndCaretSigns': 'Iki gice gisabwa kuba gifite imibare n amabara gusa',
    'validation.onlyLettersNumbersAndCaretSigns': 'Iki gice gisabwa kuba gifite inyuguti, imibare n amabara gusa',

    // Footer.tsx
    'footer.description': 'Citizen Engagement System for submitting and tracking complaints and feedback on public services in Rwanda.',
    'footer.links.title': 'Quick Links',
    'footer.links.home': 'Home',
    'footer.links.submit': 'Submit Complaint',
    'footer.links.track': 'Track Complaint',
    'footer.contact.title': 'Contact Us',
    'footer.contact.location': 'Kigali, Rwanda',
    'footer.contact.email': 'support@cesrwanda.gov.rw',
    'footer.contact.phone': '+250 788 123 456',
    'footer.copyright': 'Ivugire. All rights reserved.',

    // Feedback Section
    'feedback.selectProvincePlaceholder': 'Select province',
    'feedback.selectDistrictPlaceholder': 'Select district',
    'feedback.selectSectorPlaceholder': 'Select sector',
    'feedback.selectCellPlaceholder': 'Select cell',
    'feedback.selectVillagePlaceholder': 'Select village',
    'feedback.emailPlaceholder': 'Enter your email',
    'feedback.phonePlaceholder': 'Enter your phone number',
    'feedback.successMessage': 'Feedback sent successfully!',
    'feedback.errorMessage': 'Failed to send feedback. Please try again.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 